// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"douyin/app/video/model"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatFieldNames          = builder.RawFieldNames(&Chat{})
	chatRows                = strings.Join(chatFieldNames, ",")
	chatRowsExpectAutoSet   = strings.Join(stringx.Remove(chatFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	chatRowsWithPlaceHolder = strings.Join(stringx.Remove(chatFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheChatIdPrefix = "cache:chat:id:"
)

type (
	chatModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Chat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Chat, error)
		Update(ctx context.Context, session sqlx.Session, data *Chat) (sql.Result, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultChatModel struct {
		sqlc.CachedConn
		table string
	}

	Chat struct {
		Id         int64     `db:"id"`         // 娑堟伅id
		UserId     int64     `db:"user_id"`    // 发送用户id
		ToUserId   int64     `db:"to_user_id"` // 接收消息用户id
		Content    string    `db:"content"`
		CreateTime time.Time `db:"create_time"` // 鍒涘缓鏃堕棿
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newChatModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultChatModel {
	return &defaultChatModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`chat`",
	}
}

func (m *defaultChatModel) Insert(ctx context.Context, session sqlx.Session, data *Chat) (sql.Result, error) {
	chatIdKey := fmt.Sprintf("%s%v", cacheChatIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, chatRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.ToUserId, data.Content)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.ToUserId, data.Content)
	}, chatIdKey)
}

func (m *defaultChatModel) FindOne(ctx context.Context, id int64) (*Chat, error) {
	chatIdKey := fmt.Sprintf("%s%v", cacheChatIdPrefix, id)
	var resp Chat
	err := m.QueryRowCtx(ctx, &resp, chatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ?  limit 1", chatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatModel) Update(ctx context.Context, session sqlx.Session, data *Chat) (sql.Result, error) {
	chatIdKey := fmt.Sprintf("%s%v", cacheChatIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.ToUserId, data.Content, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.ToUserId, data.Content, data.Id)
	}, chatIdKey)
}

func (m *defaultChatModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	chatIdKey := fmt.Sprintf("%s%v", cacheChatIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, chatIdKey)
	return err
}

func (m *defaultChatModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheChatIdPrefix, primary)
}
func (m *defaultChatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ?  limit 1", chatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultChatModel) tableName() string {
	return m.table
}
