// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"douyin/app/video/model"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followFieldNames          = builder.RawFieldNames(&Follow{})
	followRows                = strings.Join(followFieldNames, ",")
	followRowsExpectAutoSet   = strings.Join(stringx.Remove(followFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	followRowsWithPlaceHolder = strings.Join(stringx.Remove(followFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheFollowIdPrefix                = "cache:follow:id:"
	cacheFollowUserIdAndtoUserIdPrefix = "cache:follow:userIdAndtoUserId:"
)

type (
	followModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Follow) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Follow, error)
		FindOneByUserIdAndToUserId(ctx context.Context, userId, toUserId int64) (*Follow, error)
		Update(ctx context.Context, session sqlx.Session, data *Follow) (sql.Result, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
		DeleteOneByUserIdAndToUserId(ctx context.Context, session sqlx.Session, userId, toUserId int64) error
	}

	defaultFollowModel struct {
		sqlc.CachedConn
		table string
	}

	Follow struct {
		Id         int64     `db:"id"`          // 鍏虫敞id
		UserId     int64     `db:"user_id"`     // 关注用户id
		ToUserId   int64     `db:"to_user_id"`  // 被关注用户id
		CreateTime time.Time `db:"create_time"` // 鍒涘缓鏃堕棿
		UpdateTime time.Time `db:"update_time"` // 更新时间
		IsFriend   int64     `db:"is_friend"`   // 0代表没有互相关注，1代表互相关注
	}
)

func newFollowModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultFollowModel {
	return &defaultFollowModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`follow`",
	}
}

func (m *defaultFollowModel) Insert(ctx context.Context, session sqlx.Session, data *Follow) (sql.Result, error) {
	followIdKey := fmt.Sprintf("%s%v%v", cacheFollowUserIdAndtoUserIdPrefix, data.UserId, data.ToUserId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, followRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.ToUserId, data.IsFriend)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.ToUserId, data.IsFriend)
	}, followIdKey)
}

func (m *defaultFollowModel) FindOne(ctx context.Context, id int64) (*Follow, error) {
	followIdKey := fmt.Sprintf("%s%v", cacheFollowIdPrefix, id)
	var resp Follow
	err := m.QueryRowCtx(ctx, &resp, followIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ?  limit 1", followRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultFollowModel) FindOneByUserIdAndToUserId(ctx context.Context, userId, toUserId int64) (*Follow, error) {
	followIdKey := fmt.Sprintf("%s%v%v", cacheFollowUserIdAndtoUserIdPrefix, userId, toUserId)
	var resp Follow
	err := m.QueryRowCtx(ctx, &resp, followIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `to_user_id` = ?  limit 1", followRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, userId, toUserId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultFollowModel) Update(ctx context.Context, session sqlx.Session, data *Follow) (sql.Result, error) {
	followIdKey := fmt.Sprintf("%s%v%v", cacheFollowUserIdAndtoUserIdPrefix, data.UserId, data.ToUserId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.ToUserId, data.IsFriend, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.ToUserId, data.IsFriend, data.Id)
	}, followIdKey)
}

func (m *defaultFollowModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	followIdKey := fmt.Sprintf("%s%v", cacheFollowIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, followIdKey)
	return err
}
func (m *defaultFollowModel) DeleteOneByUserIdAndToUserId(ctx context.Context, session sqlx.Session, userId, toUserId int64) error {
	followIdKey := fmt.Sprintf("%s%v%v", cacheFollowUserIdAndtoUserIdPrefix, userId, toUserId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `user_id` = ? and `to_user_id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, userId, toUserId)
		}
		return conn.ExecCtx(ctx, query, userId, toUserId)
	}, followIdKey)
	return err
}
func (m *defaultFollowModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheFollowIdPrefix, primary)
}
func (m *defaultFollowModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ?  limit 1", followRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFollowModel) tableName() string {
	return m.table
}
