// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: fileRpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传视频到OSS请求体
type UploadVideoByOssReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoName string `protobuf:"bytes,1,opt,name=videoName,proto3" json:"videoName,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadVideoByOssReq) Reset() {
	*x = UploadVideoByOssReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileRpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadVideoByOssReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoByOssReq) ProtoMessage() {}

func (x *UploadVideoByOssReq) ProtoReflect() protoreflect.Message {
	mi := &file_fileRpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoByOssReq.ProtoReflect.Descriptor instead.
func (*UploadVideoByOssReq) Descriptor() ([]byte, []int) {
	return file_fileRpc_proto_rawDescGZIP(), []int{0}
}

func (x *UploadVideoByOssReq) GetVideoName() string {
	if x != nil {
		return x.VideoName
	}
	return ""
}

func (x *UploadVideoByOssReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 上传视频到OSS返回体
type UploadVideoByOssResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayUrl  string `protobuf:"bytes,1,opt,name=playUrl,proto3" json:"playUrl,omitempty"`
	CoverUrl string `protobuf:"bytes,2,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
}

func (x *UploadVideoByOssResp) Reset() {
	*x = UploadVideoByOssResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileRpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadVideoByOssResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoByOssResp) ProtoMessage() {}

func (x *UploadVideoByOssResp) ProtoReflect() protoreflect.Message {
	mi := &file_fileRpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoByOssResp.ProtoReflect.Descriptor instead.
func (*UploadVideoByOssResp) Descriptor() ([]byte, []int) {
	return file_fileRpc_proto_rawDescGZIP(), []int{1}
}

func (x *UploadVideoByOssResp) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *UploadVideoByOssResp) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

// 上传视频到本地请求体
type UploadVideoByLocalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoName string `protobuf:"bytes,1,opt,name=videoName,proto3" json:"videoName,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadVideoByLocalReq) Reset() {
	*x = UploadVideoByLocalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileRpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadVideoByLocalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoByLocalReq) ProtoMessage() {}

func (x *UploadVideoByLocalReq) ProtoReflect() protoreflect.Message {
	mi := &file_fileRpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoByLocalReq.ProtoReflect.Descriptor instead.
func (*UploadVideoByLocalReq) Descriptor() ([]byte, []int) {
	return file_fileRpc_proto_rawDescGZIP(), []int{2}
}

func (x *UploadVideoByLocalReq) GetVideoName() string {
	if x != nil {
		return x.VideoName
	}
	return ""
}

func (x *UploadVideoByLocalReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 上传视频到本地返回体
type UploadVideoByLocalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayUrl  string `protobuf:"bytes,1,opt,name=playUrl,proto3" json:"playUrl,omitempty"`
	CoverUrl string `protobuf:"bytes,2,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
}

func (x *UploadVideoByLocalResp) Reset() {
	*x = UploadVideoByLocalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileRpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadVideoByLocalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoByLocalResp) ProtoMessage() {}

func (x *UploadVideoByLocalResp) ProtoReflect() protoreflect.Message {
	mi := &file_fileRpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoByLocalResp.ProtoReflect.Descriptor instead.
func (*UploadVideoByLocalResp) Descriptor() ([]byte, []int) {
	return file_fileRpc_proto_rawDescGZIP(), []int{3}
}

func (x *UploadVideoByLocalResp) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *UploadVideoByLocalResp) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

var File_fileRpc_proto protoreflect.FileDescriptor

var file_fileRpc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x47, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x42, 0x79, 0x4f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4c, 0x0a, 0x14,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x4f, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x49, 0x0a, 0x15, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4e, 0x0a, 0x16, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x55, 0x72, 0x6c, 0x32, 0x9d, 0x01, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x70,
	0x63, 0x12, 0x45, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x42, 0x79, 0x4f, 0x73, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x4f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42,
	0x79, 0x4f, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x19,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42,
	0x79, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fileRpc_proto_rawDescOnce sync.Once
	file_fileRpc_proto_rawDescData = file_fileRpc_proto_rawDesc
)

func file_fileRpc_proto_rawDescGZIP() []byte {
	file_fileRpc_proto_rawDescOnce.Do(func() {
		file_fileRpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_fileRpc_proto_rawDescData)
	})
	return file_fileRpc_proto_rawDescData
}

var file_fileRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fileRpc_proto_goTypes = []interface{}{
	(*UploadVideoByOssReq)(nil),    // 0: pb.UploadVideoByOssReq
	(*UploadVideoByOssResp)(nil),   // 1: pb.UploadVideoByOssResp
	(*UploadVideoByLocalReq)(nil),  // 2: pb.UploadVideoByLocalReq
	(*UploadVideoByLocalResp)(nil), // 3: pb.UploadVideoByLocalResp
}
var file_fileRpc_proto_depIdxs = []int32{
	0, // 0: pb.fileRpc.UploadVideoByOss:input_type -> pb.UploadVideoByOssReq
	2, // 1: pb.fileRpc.UploadVideoByLocal:input_type -> pb.UploadVideoByLocalReq
	1, // 2: pb.fileRpc.UploadVideoByOss:output_type -> pb.UploadVideoByOssResp
	3, // 3: pb.fileRpc.UploadVideoByLocal:output_type -> pb.UploadVideoByLocalResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fileRpc_proto_init() }
func file_fileRpc_proto_init() {
	if File_fileRpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fileRpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadVideoByOssReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileRpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadVideoByOssResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileRpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadVideoByLocalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileRpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadVideoByLocalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fileRpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileRpc_proto_goTypes,
		DependencyIndexes: file_fileRpc_proto_depIdxs,
		MessageInfos:      file_fileRpc_proto_msgTypes,
	}.Build()
	File_fileRpc_proto = out.File
	file_fileRpc_proto_rawDesc = nil
	file_fileRpc_proto_goTypes = nil
	file_fileRpc_proto_depIdxs = nil
}
