// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chat "douyin/app/user/cmd/api/internal/handler/chat"
	follow "douyin/app/user/cmd/api/internal/handler/follow"
	user "douyin/app/user/cmd/api/internal/handler/user"
	"douyin/app/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OptionalJWTMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleWare},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/action",
					Handler: follow.FollowOrUnFollowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friend/list",
					Handler: follow.FriendsListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/relation"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OptionalJWTMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/follow/list",
					Handler: follow.FollowListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/follower/list",
					Handler: follow.FansListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/relation"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleWare},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/action",
					Handler: chat.SendMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chat",
					Handler: chat.HistoryMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/message"),
	)
}
