// Code generated by goctl. DO NOT EDIT.
// Source: fileRpc.proto

package server

import (
	"context"

	"douyin/app/file/cmd/rpc/internal/logic"
	"douyin/app/file/cmd/rpc/internal/svc"
	"douyin/app/file/cmd/rpc/pb"
)

type FileRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileRpcServer
}

func NewFileRpcServer(svcCtx *svc.ServiceContext) *FileRpcServer {
	return &FileRpcServer{
		svcCtx: svcCtx,
	}
}

// 上传视频到OSS
func (s *FileRpcServer) UploadVideoByOss(ctx context.Context, in *pb.UploadVideoByOssReq) (*pb.UploadVideoByOssResp, error) {
	l := logic.NewUploadVideoByOssLogic(ctx, s.svcCtx)
	return l.UploadVideoByOss(in)
}

// 上传视频到本地
func (s *FileRpcServer) UploadVideoByLocal(ctx context.Context, in *pb.UploadVideoByLocalReq) (*pb.UploadVideoByLocalResp, error) {
	l := logic.NewUploadVideoByLocalLogic(ctx, s.svcCtx)
	return l.UploadVideoByLocal(in)
}
