// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id            int64  `json:"id"`
	Username      string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type Status struct {
	StatusCode uint32 `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type Video struct {
	Id            int64  `json:"id"`
	Author        User   `json:"author""`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}

type FeedReq struct {
	LastTime string `form:"last_time,optional"`
	Token    string `form:"token,optional"`
}

type FeedResp struct {
	Status
	NextTime  int64   `json:"next_time,omitempty"`
	VideoList []Video `json:"video_list,omitempty"`
}

type PublishListReq struct {
	UserId int64  `form:"user_id" validate:"required,gte=0"`
	Token  string `form:"token,optional"`
}

type PublishListResp struct {
	Status
	VideoList []Video `json:"video_list,omitempty"`
}

type PublishReq struct {
	Title string `form:"title" validate:"required,max=100,min=1"`
	Token string `form:"token" validate:"required"`
}

type PublishResp struct {
	Status
}

type FavoriteOrUnfavoriteReq struct {
	Token      string `form:"token" validate:"required"`
	VideoId    int64  `form:"video_id" validate:"required,gte=0"`
	ActionType int64  `form:"action_type" validate:"required,gte=1,lte=2"`
}

type FavoriteOrUnfavoriteResp struct {
	Status
}

type FavoriteVideosListReq struct {
	UserId int64  `form:"user_id" validate:"required,gte=0"`
	Token  string `form:"token,optional"`
}

type FavoriteVideosListResp struct {
	Status
	VideoList []Video `json:"video_list,omitempty"`
}

type Comment struct {
	Id         int64  `json:"id"`
	User       User   `json:"user""`
	Content    string `json:"content"`
	CreateDate string `json:"create_date"`
}

type CommentOrDelCommentReq struct {
	Token       string `form:"token" validate:"required"`
	VideoId     int64  `form:"video_id" validate:"required,gte=0"`
	ActionType  int64  `form:"action_type" validate:"required,gte=1,lte=2"`
	CommentText string `form:"comment_text,optional"`
	CommentId   int64  `form:"comment_id,optional"`
}

type CommentOrDelCommentResp struct {
	Status
	Comment Comment `json:"comment,omitempty"`
}

type CommentsListReq struct {
	Token   string `form:"token""`
	VideoId int64  `form:"video_id" validate:"required,gte=0"`
}

type CommentsListResp struct {
	Status
	CommentsList []Comment `json:"comment_list,omitempty"`
}
